INCLUDE 'EMU8086.INC'

.MODEL SMALL
.STACK 100H

.DATA
    D1 DW 100
    D2 DW 20

.CODE

MAIN PROC
    MOV AX,@DATA
    MOV DS, AX
    
    ;--DYNAMIC PRINTING METHOD
    MOV AX, D1
    CALL PRINT_NUM
    PRINT ' + '
    MOV AX, D2
    CALL PRINT_NUM
    PRINTN ''
    PRINT 'RESULT: '
    
    ;-- ADDITION
    ADD AX, D1
    CALL PRINT_NUM
    PRINTN ''
    
        ;--DYNAMIC PRINTING METHOD
    MOV AX, D1
    CALL PRINT_NUM
    PRINT ' - '
    MOV AX, D2
    CALL PRINT_NUM
    PRINTN ''
    PRINT 'RESULT: '
    
    ;-- SUBTRACTION
    MOV AX, D1
    SUB AX, D2
    CALL PRINT_NUM
    PRINTN ''
    
        ;--DYNAMIC PRINTING METHOD
    MOV AX, D1
    CALL PRINT_NUM
    PRINT ' * '
    MOV AX, D2
    CALL PRINT_NUM
    PRINTN ''
    PRINT 'RESULT: '
    
    ;-- MULTIPLICATION
    MUL D1
    CALL PRINT_NUM
    PRINTN ''
    
    ;--DYNAMIC PRINTING METHOD
    MOV AX, D1
    CALL PRINT_NUM
    PRINT ' / '
    MOV AX, D2
    CALL PRINT_NUM
    PRINTN ''
    PRINT 'RESULT: '
    
    ;--THE DIVISION OPERATION
    MOV AX, D1
    DIV D2           ;--ONLY REGISTER OR VARIABLE IS ACCEPTABLE FOR 'DIV' COMMAND; NOT DIRECT VALUE
    CALL PRINT_NUM
    
    
    RETURN:
    MOV AH, 4CH
    INT 21H
    
MAIN ENDP

;--DECLARING THESE PRE-DEFINED FUNCTIONS FROM 
;THE 'EMU8086.INC'FOR LATER USE IN THE PROGRAM
DEFINE_PRINT_NUM
DEFINE_PRINT_NUM_UNS
DEFINE_SCAN_NUM

END MAIN